mood_labels = [
    "Meditative",
    "Inspired",
    "Dreaming",
    "Depressed",
    "Bitter",
    "Sad",
    "Refined",
    "Sentimental",
    "Inhibited",
    "Sensual",
    "Glamourous",
    "Passionate",
    "Soothing",
    "Cool",
    "Atmospheric",
    "Cerebral",
    "Performing",
    "Determined",
    "Powerful",
    "Heroic",
    "Organic",
    "Friendly",
    "Warm-hearted",
    "Rebellious",
    "Aggressive",
    "Impulsive",
    "Innocent",
    "Happy",
    "Lively",
    "Revitalizing",
    "Energetic",
    "Free",
    "Melodramatic",
    "Humorous",
    "Fun",
]

situation_labels = [
    "Adrenaline (sports & action)",
    "Alone & reflective",
    "Appeal",
    "Autumn",
    "Background",
    "Bar",
    "Beach",
    "Beers and friends",
    "Birth & new parents",
    "Boat cruise",
    "Candle light dinner",
    "Carnival",
    "Chill",
    "City life",
    "Cocktails",
    "Cocooning",
    "Commute",
    "Countryside",
    "Darkness",
    "Dawn",
    "Dull and rainy day",
    "Faith & worship",
    "Falling in love",
    "Family",
    "Fast car & racing",
    "Fight",
    "Friday night",
    "Funeral",
    "Goodbyes",
    "Halloween",
    "Heartbreak / sorrow",
    "Homecoming",
    "Hope & promises",
    "Household chores",
    "Integrity",
    "Jealousy",
    "Late at night",
    "Life cycle",
    "Magical & enchanted",
    "Meditation",
    "Morning",
    "Nostalgia / reminiscing",
    "Office",
    "Parade",
    "Party time",
    "Pregaming",
    "Pride",
    "Protest",
    "Psychedelic (altered state of consciousness)",
    "Road trip",
    "Rodeo",
    "Romance",
    "Running",
    "Seize the day",
    "Sleep",
    "Spooky",
    "Spring",
    "Study & focus",
    "Summer",
    "Sunday morning",
    "Suspense",
    "Tailgate",
    "Uplift / motivate",
    "Wedding Party",
    "Winter",
    "Winter holiday season",
    "Workout",
    "Young days",
]

voice_labels = [
    "Low-pitched vocals",
    "High-pitched vocals",
    "Instrumental",
]

genre_labels = [
    "Ambient New Age",
    "Big Band",
    "Blues",
    "Blues Rock",
    "Bollywood",
    "Bop",
    "Breakbeat",
    "Chanson Francaise",
    "Chill Out Lounge",
    "Church Music",
    "Classical",
    "Concerto",
    "Country Rock",
    "Dance Pop",
    "Disco",
    "Dub",
    "Dubstep",
    "Easy Listening",
    "EDM",
    "Electric Blues",
    "Electro Body Music",
    "Electro Pop",
    "Eurodance",
    "Experimental Electronic Music",
    "Funk",
    "Gospel",
    "Hard Rock",
    "Hip Hop",
    "House",
    "Illbient Dark Ambient",
    "Industrial",
    "Metal",
    "New Wave",
    "Noise Music",
    "Nu Metal",
    "Opera",
    "Pop",
    "Pop Rock",
    "Prelude",
    "Punk",
    "Reggae",
    "Reggaeton",
    "Rock",
    "Rock N Roll",
    "Rock New Wave",
    "Rural Blues",
    "Soul",
    "Swing",
    "Symphony",
    "Tech House",
    "Techno",
    "Alternative Rock",
    "Country",
    "Dancehall",
    "Drum & Bass",
    "Folk",
    "IDM - Electronica",
    "Indie Rock",
    "Jazz",
    "Latin Pop - Latin Dance",
    "R&B - Nu Soul",
    "Salsa - Afro Cuban",
    "Samba - Bossa Nova - MPB",
    "Soul Jazz",
    "Speech",
    "Trip Hop",
    "Vocal Jazz",
]
