genre_to_subgenre = {
    "Alternative Music": [
        "Post Punk - Rock New Wave",
        "Electro Body Music",
        "Alternative Rock",
        "Indie Rock",
        "Punk",
        "Pop punk",
    ],
    "Ambient Groove - Trip Hop Music": ["Chill Out Lounge", "Trip Hop", "Ambient New Age"],
    "Avant Garde Music": [
        "Field Recording - Natural Sounds",
        "Industrial",
        "Illbient Dark Ambient",
        "Experimental Electronic Music",
        "Noise Music",
        "Drone",
    ],
    "Blues Music": ["Gospel", "Electric Blues", "Rural Blues", "Blues"],
    "Classical Music": [
        "Waltz",
        "Symphony",
        "Prelude - Suite - Sonata",
        "Opera",
        "Concerto",
        "Church Music",
        "Classical",
    ],
    "Country & Folk Music": ["Bluegrass", "Cajun & Zydeco", "Country", "Irish - Celtic Folk", "Folk"],
    "Electro & Dance Music": [
        "House",
        "Dance Pop",
        "Tech House",
        "Hardcore Techno - Gabber",
        "Techno",
        "Breakbeat",
        "Trance",
        "EDM",
        "Eurodance",
        "Dubstep",
        "Drum & Bass",
        "Disco",
        "IDM - Electronica",
    ],
    "Jazz Music": ["Free & Contemporary Jazz", "Bop - Fusion", "Big Band", "Vocal Jazz", "Swing", "Jazz"],
    "Latin Music": [
        "Norteno",
        "Latin Folk",
        "Merengue",
        "Tango",
        "Flamenco",
        "Mambo",
        "Afro-Cuban",
        "Mariachi",
        "Latin Pop",
        "Samba - MPB",
        "Cumbia",
        "Reggaeton",
        "Banda",
        "Bossa Nova",
        "Salsa",
        "Latin Dance",
    ],
    "Metal Music": ["Extreme metal", "Metal", "Nu Metal", "Hard Rock"],
    "Reggae, Ragga, Dub Music": ["Reggae", "Dub", "Ska - Rocksteady", "Ragga - Dancehall"],
    "Rock & Pop Music": [
        "Easy Listening",
        "Electro Pop",
        "New Wave",
        "Pop",
        "Chanson Francaise",
        "Rock",
        "Country Rock",
        "Blues Rock",
        "Pop Rock",
        "Rock N Roll & Boogie",
    ],
    "Soul & Funk Music": ["Funk", "Soul Jazz", "Soul"],
    "Speech / Spoken Word": ["Speech"],
    "Urban Music": ["Hip Hop / Rap", "Drill", "R&B - Nu Soul", "Trap"],
    "World Pop & Ethnic Music": [
        "Indian Classical",
        "Indian Pop",
        "Afropop",
        "African Traditional Music",
        "Balkan & Klezmer",
        "Bollywood",
        "Raï",
        "Arabic Pop",
    ],
}


subgenre_to_genre = {vv: k for k, v in genre_to_subgenre.items() for vv in v}
